[package]
name = "programs"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-client.workspace = true
anchor-spl.workspace = true
anyhow.workspace = true

solana-cli-config.workspace = true

escrow = { git = "https://github.com/solana-developers/program-examples.git", package = "escrow" }
clap.workspace = true
